name : "infra-preview"

on : 
  push:
    branches:
      - "main"
    paths:
      - 10_infra/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  preview:
    name: "preview"
    runs-on: ubuntu-latest
    steps:
      - run:
         echo "hellowworld"
