name : "infra-preview"

on : 
  push:
    branches:
      - "main"
    paths:
      - 10_infra/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION : 1.2.8
  AWS_REAZION : ap-northeast-1

defaults:
  run:
    shell : bash
    working-directory : "10_infra/"

jobs:
  preview:
    name: "preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{env.TF_VERSION}}
      - name: Terraform format
        run: | 
         terraform fmt -check
      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{env.AWS_REAZION}}
      - name: Terraform init
        run: | 
           terraform init -no-color